### PR TITLE
Tsl2550

### PR DESCRIPTION
**Pull request by Misca1234**
Fixing TSL2550 in opto.lib

http://ams.com/eng/content/download/250130/975613/142977

The T4 variant foot print have been re named into
AmbientLightSensor_AMS_TSL2550_SMD.kicad_mod

A 3D model have been created 

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1557

pretty push branch is
https://github.com/KiCad/Opto-Devices.pretty/pull/18

packages3D push branch is
https://github.com/KiCad/packages3D/pull/126

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/51

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
please rework the silkscreen a bit: I think the silkscreen should look like the one e.g. here:
2017-08-21 21_14_51-footprint editor no active library
or the way it looked before:
2017-08-21 21_16_01-footprint editor no active library

BTW: Is there a reason for your restyling of the footprint?

Best,
JAN

**Comment by poeschlr** [comment]
@jkriege2 In your second screenshot the silk screen seems quite near to the pads. I think we introduced a rule a few weeks ago that it should be 0.2mm from pads.

**Comment by jkriege2** [comment]
yes that may be true (it's just a screenshot of the old footprint), my point is that with the short line it is (at least not to me) clear, which pin is pin one .... the one where there is a line or the one where there is none? I think marking the corner of pin1, or having two similar lines of which one is elongated only next to pin 1 is way clearer ...

JAN

**Comment by Misca1234** [comment]
Like this ?

bild

**Comment by jkriege2** [comment]
yep, looks good to me.

**Pull request merged**
