### PR TITLE
Add LTV-817S, LTV-827S, LTV-847S

### PR DESCRIPTION
**Pull request by pointhi**
source: http://optoelectronics.liteon.com/upload/download/DS-70-96-0016/S_110_LTV-817%20%20827%20%20847%20(%20M,%20S,%20S-TA,%20S-TA1,%20S-TP%20)%20Series.pdf

ltv_827v

### CODE REVIEW

**Comment by jkriege2** [comment]
Nice! :+1:

**Comment by jkriege2** [comment]
But shouldn't the pads be maybe a bit larger to leave soe space for soldering? They pretty much end where the pins end ... maybe make them 0.5mm longer on the outside?
JAN

**Comment by pointhi** [comment]
That's the manufacture recommendation. Variations (like for Hand solder) should be marked specific.

**Comment by jkriege2** [comment]
OK, then I'll merge

**Pull request merged**
