### PR TITLE
Add footprint for LTR-303ALS-01 ambient light sensor.

### PR DESCRIPTION
**Pull request by mignon-p**
[Datasheet](http://optoelectronics.liteon.com/upload/download/DS86-2013-0004/LTR-303ALS-01_DS_V1.pdf).

ambientlightsensor

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Refer to notes I made in the symbol PR. Thanks

**Comment by jkriege2** [comment]
This may be an inconsistency, but in this repo, all footprints re prefixed with function ...

**Comment by SchrodingersGat** [comment]
Hmm.. Do we allow this, or enforce a change? I have had little to do with this repo so far. What do you think?

**Comment by jkriege2** [comment]
I used these prefixes here for several reasons:
1. some footprints already had them when coming acros thiss repo
2. They are in line with the `R_...`, `D_...`-scheme that we use elsewhere
3. It makes it easy to have an FPFilter matching all available photodiode housings ...

But that's mostly true for the more general parts for specials like above I'm not sure how to do it best ... but maybe just for aesthetics don't change the scheme  inside a single repo? + I think for most OPTO-housings, they are either general or often very specific to a single part ...

**Comment by mignon-p** [comment]
Let me know what you decide about the naming.  I'm happy to rename it, if that's still what you want to do.

**Comment by SchrodingersGat** [comment]
@jkriege2 generally speaking the footprint name should describe the package not necessarily what it is "for". e.g. `QFN` does not describe the *function* of the footprint.

I think perhaps here the `Manufacturer_MPN` is sufficient?

**Comment by jkriege2** [comment]
I would split here, between 
1. general devices like LDRs (`Resistor_LDR_`), Photodiodes (`PhotoDiode_`), PhotoTransistors (`PhotoTransistor_`), Laser-Diodes (`LaserDiode_`) that match up with a generic symbol from `device.lib`.
2. specific devices, e.g. the `LTR-303ALS-01` in this PR.

For case 1 I would leave the prefix (note we have the same for resistors, capacitors, ... as then an FPFilter in the general symbol filters out all matching fooprints
For case 2 we can drop the prefix ... The only argument that I see for the prefix is better sorting of the list of files in this repo, as all footprints with equal function are grouped and therefore it is maybe easier to find one from which to derive ... but that's just eye-candy.

Best,
JAN

**Comment by SchrodingersGat** [comment]
The distinction between generic devices (which have a generic prefix) and specific devices makes sense to me too.

**Comment by mignon-p** [comment]
> I think perhaps here the `Manufacturer_MPN` is sufficient?

OK, I've replaced `AmbientLightSensor` with the manufacturer name, `Lite-On`.

**Comment by SchrodingersGat** [comment]
Hmm seems travis doesn't know about this one.

**Pull request merged**
