### PR TITLE
Lpt80 a

### PR DESCRIPTION
**Pull request by Misca1234**
ixing LPT80A in opto.lib

http://www.osram-os.com/Graphics/XPic4/00209607_0.pdf/LPT%2080A.pdf

The foot print have been modified 
A 3D model have been created 

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1556

pretty push branch is
https://github.com/KiCad/Opto-Devices.pretty/pull/17

packages3D push branch is
https://github.com/KiCad/packages3D/pull/125

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/50

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
New symbol

bild


bild

**Comment by jkriege2** [comment]
Hi!

the courtyard should reproduce the outline of the package, i.e. the full F.Fab-outline needs to be INSIDE the courtyard. Could you please fix that?

Thanks,
JAN

**Comment by Misca1234** [comment]
Fixed 

bild

**Comment by jkriege2** [comment]
could you please round the courtyard lines onto an 0.01mm grid? (see Travis output)

Best,
JAN

**Comment by Misca1234** [comment]
Done

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
