### PR TITLE
Add a footprint for ON Semi QSE15x photosensors

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
First footprint contribution. Be patient please ;P

Datasheet: http://www.onsemi.com/pub/Collateral/QSE159-D.pdf

imagen

imagen

I do not have a 3D model nor I plan to model one in the short term.

A library symbol will be provided after my open pull request in the library repo is merged (head fork in my master branch is keeping me from performing changes without cluttering that pull request. Will change my workflow from now on)

It was not very clear for me what should footprint fields contain.

Thank you.

### CODE REVIEW

**Comment by jkriege2** [comment]
Just had a look at your footprint ... this looks really good ... just a few things need fixing, before I can merge:
1. the silkscreen is a bit close to the pins, please move the lines a few 1/10th away
2017-09-26 19_24_33-3d viewer
2. also the REF-tag on the silkscreen should move closer to the footprint itself, e.g.:
2017-09-26 19_29_01-footprint editor no active library
3. Finally you need to add a 3D model link ... you don't need to provide the model, but the link should be there, so the model is displayed, when anybody has time to make and push it! The file-link should be: `${KISYS3DMOD}/Opto-Devices.3dshapes/ONSemi_QSE15x.wrl`, offset/rotation `0,0,0`, scaling `1,1,1`

Best ... and very nice work :-)

JAN

**Comment by antoniovazquezblanco** [comment]
Fixed, Thanks!

imagen

imagen

**Comment by jkriege2** [comment]
Nice work!

Thanks,
JAN

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
