### PR TITLE
Add many additional footprints of optio-devices

### PR DESCRIPTION
**Pull request by jkriege2**
opto_device
smartdil
bd
tsl2550pcb

### CODE REVIEW

**Comment by jkriege2** [comment]
Vishay has  a naming scheme for its packages for the TSOP-IR-receivers (see http://www.vishay.com/ir-receiver-modules/list/product-82742/), so I changed the package names accordingly and added the missing pacakges:

vishay

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: PhotoDiode_SMD-DIL2_4.5x4
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
checking module: PhotoTransistor_TO-18_2Pin_CE
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
checking module: Resistor_LDR_5.1x4.3_RM3.4
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.15mm line width and provides a reference mark for pin 1. (IPC-7351).
checking module: Resistor_LDR_D6.4_RM3.4
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.15mm line width and provides a reference mark for pin 1. (IPC-7351).
checking module: Resistor_LDR_Vertical_5.2x5.2_RM3.5
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.15mm line width and provides a reference mark for pin 1. (IPC-7351).
```

I would also suggest, to split such PR in the future, so they are easier to review

**Comment by jkriege2** [comment]
OK, I hope they are all fixed now ... here it looks good ;-)

I will split the PR next time ;-) ...

**Comment by pointhi** [comment]
Please also check the KLC manually, the script only covers a part of them:
- Pad 1 is on the left first, then at the top, except at the top for PLCC (IPC-7351).
- Courtyard clearance is 0.25mm

Pretty new KLC rules:
- Fabrication layer contains an outline of the part using a 0.10mm line width.

Other things:
- remove silkscreen from pads
- I think the `C` and the arrows of the PhotoDiode footprints should be moved to the F.Fab layer
- ... (Please read the KLC carefully and check your footprints again. This was only a quick look from my side)

**Comment by jkriege2** [comment]
OK, I'll look into this.
I was thinking on reworking the footprints a bit more anyways: and combine some to one (e.g. the PhotoTransistor+PhotoDiode footprints) ... let's see.

On the other tings:
- Silk: will check
- I would leave them on the silk screen, especially the arrows, as they indicate from where the light comes, which can be handy to have printed on the PCB ... don't you think? The C was on the Silk for other diodes too ... that's why I put them there ...

Best,
JAN

**Pull request merged**
