### PR TITLE
Kps 5130

### PR DESCRIPTION
**Pull request by Misca1234**
Fixing KPS-1530 in opto.lib

http://www.kingbright.com/attachments/file/psearch/000/00/00/KPS-5130PD7C(Ver.14).pdf

The foot print have been modified 
A 3D model have been created 

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1555

pretty push branch is
https://github.com/KiCad/Opto-Devices.pretty/pull/16

packages3D push branch is
https://github.com/KiCad/packages3D/pull/124

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/49

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Could you also rename it to e.g. `ColorSensor_Kingbright_KPS-5130` in order to match the rest of the lib?

Finally I think the REFDES should be `D`. In the end this is just 3 photodiodes in a single package with one common pin. All other photodiodes are also `D`.

cu
JAN

**Comment by jkriege2** [comment]
Hi!

I also noticed you renamed color to the BE-version colour ... I don't know whether there is any consensus, which version to use ... but I beliefe (not a native speaker though) the AE version is more common world-wide, thus I would votoe to stick to that?

Best,
JAN

**Comment by Misca1234** [comment]
https://en.oxforddictionaries.com/definition/colour

If some people around the world want to use some variant, that is, some pinyin dialect of English, in order to impress some distant old grumpy cousin engineer, that still thinks that one chip CPU is some fashion trend and can not understand why anything else than the TTL 74 serie would be needed I guess it is up to them, but I will try to stick to English.

It is bad enough we have to even be aware of this complete insane fucking bullshit to mils, 
what kind of bloddy crap is that.

**Comment by jkriege2** [comment]
I do know the definition and do know the difference between the two and don't want to stamp on anyones foot, but to me the AE version simply seems more common and I fell that a world-wide open source project should stick to the more common version ... Beeing from germany I would also try and correct austrian/swiss constructs in german texts iff (and only if) they are for a wider audience, especially if you expect people to find something in the lib by searching for keywords.

To stress the more common AE point: http://www.googlebattle.com/?domain=color&domain2=colour&submit=Go%21 (I know it's the usualy google filter, but I think it has something to say about what is used) + in the KiCAD lib (searching simply through any file) I spotted 1 use of colour and 11 uses of color ... 

so, how do we proceed?

@poeschlr @SchrodingersGat @hackscribble @Shackmeister @pointhi @CarlPoirier Input on this?

Best,
JAN

**Comment by poeschlr** [comment]
I don't care which version we choose but we should definitely fix it in our rule set. 
We might want to align the policy to the kicad coding policy. As far as i can tell they use American English. (Just look at the file names in the 3d viewer "module".)
And by the way: Keep civil guys. Both of you do great work.

Also: iff means if and only if you don't need to give the detail about it in brackets. (It defeats the point of using iff)

**Comment by SchrodingersGat** [comment]
As Rene says let's all be friendly about this :)

I very much agree that the best approach is to pick a standard here and encode it in the KLC, rather than having to debate endlessly and explain to any submitter. 

I would vote for US English as it is more well known. Many manufacturers are based in the US too. Unless there's a good reason to pick the "underdog"?

That being said, as an Australian it offends me deeply that the yanks cannot spell. 

If there is consensus I will update the KLC.

@Misca1234 your contributions have been awesome, please don't let these little roadblocks dissuade you from further work :)

**Comment by jkriege2** [comment]
Hi!

so from these comments I would suggest to change colour to the AE-version color. Fine with ereyone?
@Misca1234 Could you do that change, so we can process to merge this nice contribution?

Best,
JAN

**Comment by Misca1234** [comment]
I fix it

**Comment by Misca1234** [comment]
Renamed done

**Pull request merged**
