### PR TITLE
Footprint of Hamamatsu SiPM

### PR DESCRIPTION
**Pull request by Matyro**
Here is the footprint of the hamamatsu SiPM
http://www.hamamatsu.com/resources/pdf/ssd/s13360_series_kapd1052e.pdf

this footprint is used in the pull request https://github.com/KiCad/kicad-library/pull/1115

### CODE REVIEW

**Comment by poeschlr** [comment]
Please correct the KLC errors found by the automatic test system.
https://travis-ci.org/KiCad/Opto-Devices.pretty/builds/214045023

Could you also post a screenshot of the footprint once you are done with fixing the klc errors?
Also have a look at the new kicad library convention and check that everything is ok.
https://github.com/SchrodingersGat/kicad-library/wiki/KLC
There is also a FAQ section:
https://github.com/SchrodingersGat/kicad-library/wiki/FAQ

If you have any questions just come back here.

**Comment by Matyro** [comment]
Fixed problems and added the image

sipm

**Comment by poeschlr** [comment]
Pin 1 markers are missing. (on f.fab and f.silk)

Why is there such a large offset between part body and silk outline?
The silk outline normally is placed such that it touches the fab outline. The center of the fab outline represents the maximum body size of the part. (with maximum size i mean the measurement when accounting for the tolerances given in the datasheet.) If the silk outline touches the fab line, the inner side of the lines is 0.5 mm away from the part itself.

**Comment by Matyro** [comment]
Fab line is now exactly on max size
Silk is on max size + 0.11
and crtyrd on max size + 0.25

mppc

**Comment by poeschlr** [comment]
Is there a reason your tht holes have a drill size of 0.66?
In the datasheet the drill is given as 0.46+/-0.05mm.

looks good otherwise.

**Comment by jkriege2** [comment]
Holes are fine ... altough already quite tight ... the datasheet sais the WIREs are 0.46mm in diameter, so the holes should be larger!

Nice work on this one!

Thanks,
JAN

**Pull request merged**
