### PR TITLE
Lg206 x

### PR DESCRIPTION
**Pull request by Misca1234**
LG1206L
Alias LG206D

http://kodenshi.co.jp/products/pdf/sensor/photointerrupter_ic/LG205L.pdf
http://kodenshi.co.jp/products/pdf/sensor/photointerrupter_ic/LG206D.pdf

kicad-libaray push
https://github.com/KiCad/kicad-library/pull/1545

Opto-Devices.pretty
https://github.com/KiCad/Opto-Devices.pretty/pull/14

packages3D
https://github.com/KiCad/packages3D/pull/120

packages3D-source
https://github.com/KiCad/packages3D-source/pull/44

bild

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

this footprint is missing the refdes on the F.Fab layer and would benefit from making pin1 rectangular:
2017-08-18 20_01_13-footprint editor no active library

Also the pins 1,2,3 should be separated 2mm, but 4,5 should be separated by 2.54mm, see DS:
2017-08-18 20_03_18-lg205l pdf geschutzt - adobe acrobat reader dc

Finally the copper-ring around the pins should be increased (which is possible as the pins will move further apart).
Best,
JAN

**Comment by Misca1234** [comment]
new look

bild

**Comment by jkriege2** [comment]
Hi!

looks good now ... having a closer look at the datasheets: The difference between the D and L-version is that the D-version has small nibbles to position the device properly on the PCB ... i.e. the footprint above is really only for the L-version. Could you derive a second one for the D-version, which has the nibbles (diameter =0.7mm, so there should be fine drill-holes with say 0.8mm diameter):
2017-08-18 22_09_24-lg206d pdf geschutzt - adobe acrobat reader dc

**Comment by Misca1234** [comment]
The width is also different, one is 6 mm and the other one is 6.2 mm but I thought it would not matter
But I will split them into 2 different footprints, 3D models and symbols

**Comment by Misca1234** [comment]
bild

bild

**Comment by jkriege2** [comment]
I think that this drawing is a bottom view (judging from the photo on p.1 of the DS it is):
2017-08-18 23_29_59-lg206d pdf geschutzt - adobe acrobat reader dc
Then the holes should be mirrored ... 

Best,
JAN

**Comment by Misca1234** [comment]
bild

bild

**Comment by jkriege2** [comment]
I think that this drawing is a bottom view (judging from the photo on p.1 of the DS it is):
2017-08-18 23_29_59-lg206d pdf geschutzt - adobe acrobat reader dc
Then the holes should be mirrored ... 

Best,
JAN

**Comment by Misca1234** [comment]
Yes, it is also visible on the image on top left of first page

**Comment by Misca1234** [comment]
bild

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Comment by Misca1234** [comment]
I think you forgot to merge this branch

**Pull request merged**
